#pragma once

#define SDK_VERSION_MAJOR 1
#define SDK_VERSION_MINOR 2
#define SDK_VERSION_PATCH 2

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define SDK_VERSION_STRING STR(SDK_VERSION_MAJOR) "." STR(SDK_VERSION_MINOR) "." STR(SDK_VERSION_PATCH)
